apiVersion: databricks.microsoft.com/v1alpha1
kind: SecretScope
metadata:
  name: ds-eventhubs
spec:
  initial_manage_permission: users
  secrets:
    - key: ConnectionString
      value_from:
        secret_key_ref:
          name: eventhubnamespace-secret
          key: ConnectionString
    - key: EventhubName
      string_value: twitter
    - key: EventhubNamespace
      value_from:
        secret_key_ref:
          name: eventhubnamespace-secret
          key: EventhubNamespace
    - key: SharedAccessKey
      value_from:
        secret_key_ref:
          name: eventhubnamespace-secret
          key: SharedAccessKey
    - key: SharedAccessKeyName
      value_from:
        secret_key_ref:
          name: eventhubnamespace-secret
          key: SharedAccessKeyName
    - key: ConnectionString
      value_from:
        secret_key_ref:
          name: eventhubnamespace-secret
          key: ConnectionString
  acls:
    - principal: azkhojan@microsoft.com
      permission: READ
