apiVersion: databricks.microsoft.com/v1alpha1
kind: SecretScope
metadata:
  name: ds-twitters
spec:
  initial_manage_permission: users
  secrets:
    - key: TwitterAPIkey
      value_from:
        secret_key_ref:
          name: mytwittersecret
          key: TwitterAPIkey
    - key: TwitterAPISecret
      value_from:
        secret_key_ref:
          name: mytwittersecret
          key: TwitterAPISecret
    - key: TwitterAccessToken
      value_from:
        secret_key_ref:
          name: mytwittersecret
          key: TwitterAccessToken
    - key: TwitterAccessSecret
      value_from:
        secret_key_ref:
          name: mytwittersecret
          key: TwitterAccessSecret
  acls:
    - principal: azkhojan@microsoft.com
      permission: READ
